[package]
name = "collect"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
borsh = "0.9"
log = "0.4.14"
env_logger = "0.9.0"
structopt = "0.3.21"
solana-client = "1.14.13"
solana-sdk = "1.14.13"
solana-program = "1.14.13"
solana-account-decoder = "1.14.13"
solana-config-program = "1.14.13"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
serde_json = "1.0"
anchor-lang = "0.26.0"
num = "0.4.0"
bincode = "1.3.3"
reqwest = "0.11.11"
chrono = "0.4"
spl-governance = "3.1"